portal-hq/PortalSwift

Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Components/PortalWebView.swift

This PR makes the webView and webViewContentIsLoaded variables `public` in the `PortalWebView` class.
- Manual tests in staging: Pending
- E2E tests in Datadog: Pending

Make the webview + webview content loaded public

---

Cocoapods Example/Pods/Pods.xcodeproj/project.pbxproj
Cocoapods Example/PortalSwift/WebViewController.swift
SPM Example/PortalSwift/WebViewController.swift
Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Components/PortalWebViewDelegate.swift

This exposes a `PortalWebViewDelegate` protocol, allowing customers to hook into the `decidePolicyFor` delegate method. This will unblock Bitso in setting up WalletConnect deep linking.
- Manual tests in staging: Pending
- E2E tests in Datadog: No

HOTFIX - ENG-1980 - Add support for PortalWebViewDelegate

---

Cocoapods Example/Pods/Pods.xcodeproj/project.pbxproj
Cocoapods Example/PortalSwift/WebViewController.swift
PortalSwift.podspec
SPM Example/PortalSwift/WebViewController.swift
Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Components/PortalWebViewDelegate.swift
Sources/PortalSwift/Mocks/Core/MockPortal.swift
Sources/PortalSwift/Portal.swift

This PR adds support for `MockPortal` to have an initializer to bypass HTTP requests made by `Portal`. It also updates `Portal` to support the `isMocked` flag to ensure that child instances are mocked when initialized via the `MockPortal` class.
This is to unblock Intuit as they integrate `Portal` into their app and testing framework.
- Manual tests in staging: Yes
- E2E tests in Datadog: No

ENG-1922 - Add mocks support

---

Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Storage/Passkey/PasskeyAuth.swift

This PR ensures we guard instead of force unwrapping in signerRequestCompletion in the WebView.
- Manual tests in staging: Pending
- E2E tests in Datadog: Pending

Kelsonic david/fix webview panic

---

Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Connect/PortalConnect.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Core/PortalApi.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Core/mpc/MpcMobileProtocol.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Core/mpc/PortalMpc.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Mocks/Core/MockPortalApi.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Portal.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Provider/MpcSigner.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Provider/PortalProvider.swift
Cocoapods Example/PortalSwift/Base.lproj/Main.storyboard
Cocoapods Example/PortalSwift/Portal.swift
Cocoapods Example/PortalSwift/ViewController.swift
Cocoapods Example/Tests/e2e/PasswordWalletTests.swift
Cocoapods Example/Tests/e2e/ProviderTests.swift
Cocoapods Example/Tests/e2e/WalletTests.swift
SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/Portal.swift
SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Connect/PortalConnect.swift
Sources/PortalSwift/Core/PortalApi.swift
Sources/PortalSwift/Core/mpc/MpcMobileProtocol.swift
Sources/PortalSwift/Core/mpc/PortalMpc.swift
Sources/PortalSwift/Mocks/Core/MockPortal.swift
Sources/PortalSwift/Mocks/Core/MockPortalApi.swift
Sources/PortalSwift/Portal.swift
Sources/PortalSwift/Provider/MpcSigner.swift
Sources/PortalSwift/Provider/PortalProvider.swift

This PR enables multi-backup functionality by completing the following tickets:
- Allow multiple backing up and recovering with multiple backups.
- Update MpcShare type to include optional backupSharePairId.
- Update recoverBackup
- Update portal.backup
- Add api endpoint handler portal.api.getBackupShareMetadata (array of backup share pair records, includes { backupSharePairId }) for new endpoint.
- Update storedClientBackupShareKey API request to pass in backupSharePairId in the request body
- Update recoverSigning
https://linear.app/portal-hq/issue/ENG-2215/allow-multiple-backing-up-and-recovering-with-multiple-backups
https://linear.app/portal-hq/issue/ENG-2214/update-mpcshare-type-to-include-optional-backupsharepairid
https://linear.app/portal-hq/issue/ENG-2212/update-recoverbackup …

Add support for v6

---

PortalSwift.xcworkspace/xcshareddata/swiftpm/Package.resolved
SPM Example/SPM Example.xcodeproj/project.pbxproj
SPM Example/Tests/e2e/PasswordWalletTests.swift
SPM Example/Tests/e2e/WalletTests.swift
Sources/Frameworks/mpc.xcframework/Info.plist
Sources/Frameworks/mpc.xcframework/ios-arm64/Mpc.framework/Headers/Mobile.objc.h
Sources/Frameworks/mpc.xcframework/ios-arm64/Mpc.framework/Info.plist
Sources/Frameworks/mpc.xcframework/ios-arm64/Mpc.framework/Resources/Info.plist
Sources/Frameworks/mpc.xcframework/ios-arm64_x86_64-simulator/Mpc.framework/Headers/Mobile.objc.h
Sources/Frameworks/mpc.xcframework/ios-arm64_x86_64-simulator/Mpc.framework/Info.plist
Sources/Frameworks/mpc.xcframework/ios-arm64_x86_64-simulator/Mpc.framework/Resources/Info.plist

- This PR builds the binary using xcode 15.3.
- Tested building example app using xcode 15.3 and 15.2.
** This PR will add the binary that includes all the multi wallet functions but they will still not be exposed to the user by the sdk.
- E2E: Pending

HOTFIX: Updating binary for xcode version 15.3

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ConnectViewController.swift

- Created new label in ConnectViewController - Main.storyboard for Disconnected state
- Checked for Connected state is true then updated disconnect label with Disconnected 🛑
- Checked for Disconnected state is true then updated disconnect label with Disconnected ✅
Note: When clicked on disconnected button, callback is not getting updated for the disconnected state that is why Diconnected ✅ is not working, as soon as this is fixed in SDK this will updated

Code fix for ENG-3012

---

SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Portal.swift
Sources/PortalSwift/Provider/PortalProvider.swift
Sources/PortalSwift/Storage/Passkey/PasskeyStorage.swift

- **Portal.Swift**: Updated `apikey` to internal because it is used in the `PortalWebViewClass`.
- **PortalProvider.swift**: Made the `apikey` private.
- **PasskeyStorage.swift**: Updated `apikey` to internal because it is used in the `PortalMPC.swift` class.
- **ViewController.swift**: Commented out code that uses `apikey` since it was previously public.
- Other than these changes, there are 6 classes that are already using `apikey` as private.

ENG-3108 - ApiKey has to be private if it is not already

---

Sources/PortalSwift/Provider/PortalProvider.swift

- updated code in PortalProvider.swift for removing listener in case of signing approved or signing rejected

ENG-3069-clean once revent handler

---

SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Provider/PortalProvider.swift
Sources/PortalSwift/Utils/EventBus.swift

- calling emit function multiple times for same event was causing the crash
- added a check using guard in PortalProvider.swift and EventBus.swift to check if the registered evnt is not nil
- added test code in viewcontroller to verify decline condition

ENG-2809-Add check for params before calling count

---

Sources/PortalSwift/Provider/PortalProvider.swift

- updated code in PortalProvider.swift for removing listener in case of signing approved or signing rejected

Fix once event handler cleanup issue

---

Sources/PortalSwift/Provider/PortalProvider.swift

- The crash occurred while setting `self.events[event] = event`. This issue arose due to multiple classes potentially calling the same function simultaneously, leading to a concurrency-related race condition. To address this crash, I corrected the variable assignment to ensure proper handling under concurrent execution.

ENG-3177-crash

---

Sources/PortalSwift/Mocks/Constants.swift
Sources/PortalSwift/Mocks/Utils/MockWebSocketClient.swift
Tests/PortalSwiftTests/PortalConnectTest.swift

- MockConstants.swift - updated some values that are needed to write test case.
- created new class PortalConnectTest and MockWebSocketClient
- added test cases for following methods: connect
disconnect
handleClose
handleDappSessionRequested
handleSessionRequest
handleSessionRequestAddress
handleSessionRequestTransaction
handleProviderRequest - can not add test case for this because this is private method

Added test case for PortalConnect.swift

---

Cocoapods Example/PortalSwift/Portal.swift
Cocoapods Example/PortalSwift/ViewController.swift
Cocoapods Example/Tests/e2e/PasswordWalletTests.swift
Cocoapods Example/Tests/e2e/ProviderTests.swift
Cocoapods Example/Tests/e2e/WalletTests.swift
PortalSwift.xcworkspace/xcshareddata/swiftpm/Package.resolved
SPM Example/PortalSwift/ViewController.swift
SPM Example/Tests/e2e/PasswordWalletTests.swift
SPM Example/Tests/e2e/ProviderTests.swift
SPM Example/Tests/e2e/WalletTests.swift
Sources/PortalSwift/Core/Mpc/Mobile/MpcMobileProtocol.swift
Sources/PortalSwift/Core/Mpc/PortalMpc.swift
Sources/PortalSwift/PortalTypes.swift
Sources/PortalSwift/Provider/MpcSigner/PortalMpcSigner.swift

This PR removes `optimized` as a feature flag and instead always sets it to `true` when passing it to MPC binary methods.
- Breaking Changes: Yes, must remove `optimized` feature flag
- Performance impact: Yes, customers will always be using pre-generated primes

Don't make feature flags optimized configurable, set it to true always

---

SPM Example/PortalSwift/ViewController.swift

Add success / fail message to the UI with the result of deleting keychain when click on the "Delete Keychain" button.
Add success / fail message to the UI with the result of deleting keychain when click on the "Delete Keychain" button.
- Unit tests added:  No
- E2E tests added:  No
- Metrics, logs, or traces added:  No

[Example] Add success / fail message to the UI with the result of deleting keychain

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift

remove the simulate transaction button as it is already tested in the api methods.
Before:
After:

[Example] remove the simulate transaction button

---

Sources/PortalSwift/Core/Mpc/PortalMpc.swift
Sources/PortalSwift/Utils/PortalEncryption.swift

Resolves an issue with `continuation.resume(throwing:)` not returning after. Resulting in the logging of shares on the machine.

HOTFIX - Ensure continuations return when throwing

---

Sources/PortalSwift/Core/Mpc/PortalMpc.swift

Resolves issue with `isMultiBackupEnabled` feature flag not being passed to MPC `backup` and `recover` operations

HOTFIX - Fix missing `isMultiBackupEnabled`

---

Sources/PortalSwift/Core/Mpc/PortalMpc.swift

Fixes the recover logic if a customer hasn't backed up their solana share.

Fix recover bug

---

.swiftpm/xcode/xcshareddata/xcschemes/Unit Tests.xcscheme
SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Core/Api/PortalApi.swift
Sources/PortalSwift/Core/Api/PortalApiTypes.swift
Sources/PortalSwift/Mocks/Constants.swift
Sources/PortalSwift/Mocks/Utils/MockPortalRequests.swift
Sources/PortalSwift/Portal.swift
Sources/PortalSwift/PortalTypes.swift
Tests/PortalSwiftTests/Core/PortalApiTests.swift
Tests/PortalSwiftTests/PortalApi/PortalApiMock.swift
Tests/PortalSwiftTests/PortalApi/PortalApiSpy.swift
Tests/PortalSwiftTests/PortalTests.swift
Tests/PortalSwiftTests/Stubs/FundResponse.swift
Tests/PortalSwiftTests/Stubs/SendAssetParams.swift

This PR adds `portal.api.fund` and `portal.receiveTestnetAsset`, which currently only supports `eip155:11155111` + `ETH` in the amount of `0.001` or less per client per day.
This PR also adds support for `portal.sendAsset`.
- Documentation updated: Pending

Add portal.api.fund  + portal.receiveTestnetAsset + portal.sendAsset
