Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Components/PortalWebView.swift
Cocoapods Example/PortalSwift/WebViewController.swift
SPM Example/PortalSwift/WebViewController.swift
Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Provider/PortalProvider.swift

2.0.14 Release

---

Sources/PortalSwift/Portal.swift

This PR adds convenience methods for `ethEstimateGas` and `ethGasPrice`
- Manual tests in staging: Yes
- E2E tests in Datadog: No

ENG-1767 - Add convenience methods for `ethEstimateGas` and `ethGasPrice`

---

Cocoapods Example/Cocoapods Example.xcodeproj/project.pbxproj
Cocoapods Example/PortalSwift/Base.lproj/Main.storyboard
Cocoapods Example/PortalSwift/Portal.swift
Cocoapods Example/PortalSwift/ViewController.swift
Cocoapods Example/Tests/e2e/PasswordWalletTests.swift
SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/Portal.swift
SPM Example/PortalSwift/ViewController.swift
SPM Example/SPM Example.xcodeproj/project.pbxproj
SPM Example/Tests/e2e/PasswordWalletTests.swift
Sources/Frameworks/mpc.xcframework/Info.plist
Sources/Frameworks/mpc.xcframework/ios-arm64/Mpc.framework/Headers/Mobile.objc.h
Sources/Frameworks/mpc.xcframework/ios-arm64_x86_64-simulator/Mpc.framework/Headers/Mobile.objc.h
Sources/PortalSwift/Core/PortalApi.swift
Sources/PortalSwift/Core/mpc/MpcMobile.swift
Sources/PortalSwift/Core/mpc/MpcMobileProtocol.swift
Sources/PortalSwift/Core/mpc/PortalMpc.swift
Sources/PortalSwift/Mocks/Constants.swift
Sources/PortalSwift/Mocks/Core/MockMpc/MockMpcMobile.swift
Sources/PortalSwift/Mocks/Core/MockMpc/MockMpcMobileErrors.swift
Sources/PortalSwift/Mocks/Core/MockMpc/MockPortalMpc.swift
Sources/PortalSwift/Mocks/Core/MockPortalApi.swift
Sources/PortalSwift/Portal.swift
Tests/PortalSwiftTests/Core/PortalCoreTests.swift

Reverts portal-hq/PortalSwift#224
This PR was accidentally merged into main and should be going into release-candidate instead. Reverting this now

Revert "Parsa/eject tests"

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/Portal.swift

Keeping history of main consistent with release candidate.

Fixing bug with SPM example app backup method

---

Cocoapods Example/Cocoapods Example.entitlements
Cocoapods Example/PortalSwift/ConnectViewController.swift
Cocoapods Example/PortalSwift/Portal.swift
Cocoapods Example/PortalSwift/ViewController.swift
SPM Example/PortalSwift/ConnectViewController.swift
SPM Example/PortalSwift/Portal.swift
SPM Example/PortalSwift/ViewController.swift
SPM Example/SPM Example.entitlements

- Updates all of the constants for staging domains
- Performance impact: Np
- Unit tests added: No, N/A
- E2E tests added: No, N/A
- Manual tests in staging: N/A
- E2E tests in Datadog: N/A

Staging Domain Update: Update staging domain constants

---

Cocoapods Example/Cocoapods Example.entitlements
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Connect/PortalConnect.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Core/PortalApi.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Core/mpc/MpcMobileProtocol.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Core/mpc/PortalMpc.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Mocks/Core/MockPortalApi.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Portal.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Provider/MpcSigner.swift
Cocoapods Example/Pods/PortalSwift/Sources/PortalSwift/Provider/PortalProvider.swift
Cocoapods Example/PortalSwift/Base.lproj/Main.storyboard
Cocoapods Example/PortalSwift/ConnectViewController.swift
Cocoapods Example/PortalSwift/Portal.swift
Cocoapods Example/PortalSwift/ViewController.swift
Cocoapods Example/Tests/e2e/PasswordWalletTests.swift
Cocoapods Example/Tests/e2e/ProviderTests.swift
Cocoapods Example/Tests/e2e/WalletTests.swift
SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ConnectViewController.swift
SPM Example/PortalSwift/Portal.swift
SPM Example/PortalSwift/ViewController.swift
SPM Example/SPM Example.entitlements
Sources/PortalSwift/Connect/PortalConnect.swift
Sources/PortalSwift/Core/PortalApi.swift
Sources/PortalSwift/Core/mpc/MpcMobileProtocol.swift
Sources/PortalSwift/Core/mpc/PortalMpc.swift
Sources/PortalSwift/Mocks/Core/MockPortal.swift
Sources/PortalSwift/Mocks/Core/MockPortalApi.swift
Sources/PortalSwift/Portal.swift
Sources/PortalSwift/Provider/MpcSigner.swift
Sources/PortalSwift/Provider/PortalProvider.swift

[Your PR description here]
- Checked against coding style guide: Yes|No
- Manual tests in staging: Pending
- E2E tests in Datadog: Pending
- Changelog updated: Yes|No

Release candidate

---

Cocoapods Example/Cocoapods Example.entitlements
Cocoapods Example/PortalSwift/ViewController.swift
Pods.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift
SPM Example/SPM Example.entitlements
Sources/PortalSwift/Storage/Passkey/PasskeyAuth.swift
Sources/PortalSwift/Storage/Passkey/PasskeyStorage.swift

Allows a user to set the relying party themselves

Configurable Relying Party

---

SPM Example/PortalSwift/Portal.swift
SPM Example/PortalSwift/ViewController.swift
Sources/Frameworks/mpc.xcframework/ios-arm64/Mpc.framework/Headers/Mobile.objc.h
Sources/Frameworks/mpc.xcframework/ios-arm64_x86_64-simulator/Mpc.framework/Headers/Mobile.objc.h

New Binary that removes local network permission request on app start.

Remove local network permission request

---

.gitignore
Package.resolved

Ensures that we're committing our `Package.resolved` file so we can track dependency versions
- Checked against coding style guide: N/A
- Documentation updated: N/A
- Breaking Changes: N/A
- Performance impact: N/A
- Unit tests added: N/A
- E2E tests added: N/A
- Manual tests in staging: N/A
- E2E tests in Datadog: N/A
- Changelog updated: Yes|No

Don't ignore Package.resolved

---

PortalSwift.podspec
Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Provider/PortalProvider.swift

Fixes WebView's wallet_switchEthereumChain handler for Base (and any chainId greater than 255).

Hotfix merge into main: Fixes WebView's wallet_switchEthereumChain handler for Base (and any chainId greater than 255).

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift

- Added new button in Main.storyboard for testSimulateTransactionButton
- Added showToastView to show message
- Added code in multiple places to show Toast
- code update for adding Status view in Viewcontroller
- Added new button Test Simulate Transaction
https://github.com/portal-hq/PortalSwift/assets/16712848/13df0e52-93fe-4cbd-a191-f54640d19668

ENG-3070 and ENG-3067

---

Maintaining.md

Updates the `Maintaining.md` file to include new Cocoapods instructions for the example app.

Update `Maintaining.md` to include new Cocoapods instructions

---

Sources/PortalSwift/Portal.swift

Reverts portal-hq/PortalSwift#304

Revert "ENG-2990-Added deprecated message to Portal Class"

---

Sources/PortalSwift/Portal.swift

- Added @available(*, deprecated, renamed: “recoverWallet”, message: “Please use the async implementation of recoverWallet()“) message to **provisionWallet** method
- Added @available(*, deprecated, renamed: “request”, message: “Please use the async/await implementation of PortalProvider request().“) message to following methods: 
**ethEstimateGas **
**ethGasPrice**
**ethGetBalance**
**ethSendTransaction**
**ethSign**
**ethSignTransaction**
**ethSignTypedDataV3**
**ethSignTypedData**
**personalSign**
**request**
[Your PR description here]

ENG-2990-Added Description message to Portal Class

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift

- Removed dynamic added view in screen and added a static label at top of screen for showing status

ENG-3186-added static field at top of screen for status

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift

- Updated DApp Browser button y postion
- Added Txn hash in logs

updated UI

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift

set status label always visisble

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ViewController.swift

updated UI for showing TxnHash when pressed on sen1 wei button

updated UI for showing TxnHash when pressed on sen1 wei button

---

SPM Example/PortalSwift/ViewController.swift

- Updated code to set Success and failure text with icons
- Added error description in case of error to show in UI

ENG-3283-added success and failure text with icon

---

SPM Example/PortalSwift/ViewController.swift

- In the UI, the error displayed was from the localized description, which is sometimes insufficient to show the exact error. I have now added code to show the error directly, providing a more detailed description.

updated error UI to show exact error

---

.github/workflows/unit-test.yml
Sources/PortalSwift/Utils/WebSocketClient.swift
Sources/PortalSwift/Utils/WebsocketMessageTypes.swift
Tests/PortalSwiftTests/Storage/GDriveStorageTests.swift

- Added code for disconnect callback not responding back

ENG-3129-V3

---

Tests/PortalSwiftTests/Utils/EventBusTest.swift

created new class for EventBus unit test

Prakash eng 1677 eventbus unittest

---

.github/workflows/release.yml
PortalSwift.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/PortalSwift/Core/Mpc/Mobile/MpcMobileProtocol.swift
Sources/PortalSwift/Core/Mpc/PortalMpc.swift
Sources/PortalSwift/Provider/MpcSigner/PortalMpcSigner.swift
Sources/PortalSwift/Utils/Version.swift
scripts/update_version_file.sh

This PR adds `metadata.clientPlatformVersion`.

Add clientPlatformVersion

---

SPM Example/PortalSwift/ViewController.swift

Refactor the "API Methods" test code for simulate transaction to have the correct toAddress.

[Example] Refactor the "API Methods" test code for simulate transaction

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard

change the **Test Simulate Transaction** button position.
And hide the **Send UNI** button until we implement the helper functions for sending erc20 tokens.

change the "Test Simulate Transaction" button possition.

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ConnectViewController.swift

This PR adds `requestId` and `topic` WalletConnect fields to the example app for easier testing.

Update connect view controller with WC fields

---

SPM Example/PortalSwift/Base.lproj/Main.storyboard
SPM Example/PortalSwift/ConnectViewController.swift
SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Connect/PortalConnect.swift

This PR adds 2 new fields and a toggle, specifically:
1. A session `requestId` field.
2. A session `topic` field.
3. A toggle for auto approving session requests.

Add auto approve toggle

---

SPM Example/PortalSwift/ViewController.swift

Load the ETH balance when signing in, and after funding the wallet
https://github.com/user-attachments/assets/46468b05-023d-462f-9258-7a804af14841

[Example] [ETH Balance] Load the ETH balance when signing in, and after funding the wallet

---

SPM Example/PortalSwift/ViewController.swift

The Example App where crashing when sign up as the wallet address was loading as non-optional.

[Example] [Sign Up] load the address optionally.

---

.github/workflows/upload-ipa-to-muuktest.yml

update the ios spm example app release script to execute muuktest 

Ahmed/eng 3844 update the ios spm example app release script to execute muuktest 

---

Sources/PortalSwift/Core/Keychain/PortalKeychain.swift
Sources/PortalSwift/Provider/PortalProvider.swift

Resolves an issue Floor found when upgrading to `main`:
- Stops using enum-based list of Chains for `chainId`
- Resolves issue in `catch` logic during Keychain lookups

HOTFIX - Fix Floor issues

---

Sources/PortalSwift/Connect/PortalConnect.swift
Sources/PortalSwift/Portal.swift
Tests/PortalSwiftTests/PortalConnectTest.swift

Ensures FeatureFlags get passed along to PortalConnect Provider instances.

ENG-3918 - Pass feature flags to PortalConnect Provider

---

.swiftformat
Sources/PortalSwift/Core/Keychain/PortalKeychain.swift
Sources/PortalSwift/Core/Mpc/PortalMpc.swift
Sources/PortalSwift/Mocks/Core/MockPortalKeychain.swift
Sources/PortalSwift/Portal.swift
Sources/PortalSwift/Provider/MpcSigner/PortalMpcSigner.swift

- Resolves the three async functions that return optionals
- `Portal.getAddress(forChain)` - This is in the customer code path
- `Keychain.getAddress(forChain)` - This is in the customer code path via `Portal.getAddress()`
- `PortalMpcSigner.prepareParams()` - This is not in the customer code path, but it's the only other case of this, so resolved to keep the pattern across the codebase

ENG-3920 - Resolve async optional functions

---

SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Components/PortalWebView.swift
Sources/PortalSwift/Provider/PortalProvider.swift
Sources/PortalSwift/Provider/PortalProviderTypes.swift

Floor requested that we include the chainId in the approval hooks from the WebView so they can use it in their checks.
This PR adds that.

HOTFIX - Include chainId in approval data from WebView

---

Sources/PortalSwift/Mocks/Core/MockPortalKeychain.swift
Sources/PortalSwift/Portal.swift

- Updates deprecation message with broken docs link
- Makes `MockPortalKeychain` legacy-safe (per Floor's example code)

Floor medium and low priority items

---

SPM Example/PortalSwift/ViewController.swift

[Example] Print the Solana address after recover.

[Example] Print the Solana address after recover.

---

SPM Example/PortalSwift/Info.plist

Enforce the SPM Example App to be Light mode always.
Before: 
After:
- E2E tests added:  No

[Example] Enforce the example App to be Light mode always.

---

Sources/PortalSwift/Components/PortalWebView.swift

Change the class to be open to enable inheritance.

[PortalWebView] Change the class to be open to enable inheritance.

---

Sources/PortalSwift/Core/Mpc/PortalMpc.swift

HOTFIX - Add error handling to eject

---

SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Portal.swift
Sources/PortalSwift/Provider/PortalProvider.swift

- Adds support for default RPC URLs
- Adds conditional `Authorization` header to Provider RPC requests
- Updates example app to use the default RPC Config

Add support for default RPC URLs

---

SPM Example/PortalSwift/ViewController.swift

Add test example to executing `sol_getTransaction` request

Add test example to executing `sol_getTransaction` request

---

Sources/PortalSwift/Connect/PortalConnectTypes.swift

delete an empty file.

---

SPM Example/PortalSwift/ViewController.swift
Sources/PortalSwift/Connect/PortalConnectTypes.swift
Sources/PortalSwift/Core/Api/PortalApi.swift
Sources/PortalSwift/Core/Api/PortalApiTypes.swift
Sources/PortalSwift/Portal.swift
Sources/PortalSwift/Provider/PortalProvider.swift
Sources/PortalSwift/Provider/PortalProviderTypes.swift

- Some threading enhancements.
- Evaluate transaction function using evaluate endpoint.
- sol_getTransaction RPC request.
- Pass the progressCallback to mpc generateSolanaWalletAndBackupShares function.

Release 3.2.3

---

.github/workflows/upload-ipa-to-muuktest.yml

disable the muuktest release pipeline.

disable the muuktest release pipeline.
